# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutisCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='misc', max_length=25, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='OutisComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='content')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('up', models.IntegerField(default=0, verbose_name='up')),
                ('down', models.IntegerField(default=0, verbose_name='down')),
            ],
        ),
        migrations.CreateModel(
            name='OutisPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('link', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('tag', models.CharField(max_length=100, verbose_name='tag')),
                ('up', models.IntegerField(default=0, verbose_name='up')),
                ('down', models.IntegerField(default=0, verbose_name='down')),
                ('attraction', models.FileField(upload_to=b'')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('comment_number', models.IntegerField(default=0)),
                ('keep_number', models.IntegerField(default=0)),
                ('authord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outis_post.OutisCategory')),
            ],
        ),
        migrations.AddField(
            model_name='outiscomment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outis_post.OutisPost'),
        ),
        migrations.AddField(
            model_name='outiscomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
